name: Web Page Test
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: WebPageTest Action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Node Setup
        uses: actions/setup-node@v1

      - name: Install Packages
        run: npm install

      - name: Prepare Build
        run: npm run build

      - name: PM2 Install
        run: npm i pm2@latest -g

      - name: PM2 Start
        run: pm2 --name Web-Test start app.js
      # - run: serve -s build

      - name: WebPageTest
        uses: abdulsuhail/web-test@master
        with:
          apiKey: ${{ secrets.WPT_API_KEY }}
          urls: |
            localhost:9000

          label: 'GitHub Action Test'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          wptOptions: '/.github/workflows/wpt-options.json'