name: Web Page Test
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: WebPageTest Action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Node Setup
        uses: actions/setup-node@v1

      - name: Install Packages
        run: npm install

      - name: Install pm2
        run: npm install pm2@latest -g
        
      - name: Start App
        run: pm2 start app.js

      - name: WebPageTest
        uses: abdulsuhail/web-test@master
        with:
          apiKey: ${{ secrets.WPT_API_KEY }}
          urls: |
            ${{env.WPT_URL}}

          label: 'GitHub Action Test'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          wptOptions: '/.github/workflows/wpt-options.json'