name: Web Page Test
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: WebPageTest Action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Node Setup
        uses: actions/setup-node@v1

      - name: Install Project Dependencies
        run: npm install

      - name: Install pm2
        run: npm install pm2@latest -g


      - name: Run Build
        run: npm run build

      - name: Start App
        run: pm2 start app.js 

      - name: WebPageTest
        uses: abdulsuhail/web-test@master
        with:
          with_ngrok: false
          apiKey: ${{ secrets.WPT_API_KEY }}
          label: 'GitHub Action Test'
          urls: |
            https://www.google.com/search?q=mac+m1+chip
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          wptOptions: '/.github/workflows/wpt-options.json'
