name: Web Page Test
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: WebPageTest Action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Node Setup
        uses: actions/setup-node@v1

      - name: Install Packages
        run: npm install

      # - name: Update Ubuntu Box
      #   run: sudo apt update && sudo apt upgrade
      # - name: Download Curl
      #   run: sudo apt install curl

      - name: Download ngrok
        run: npm i ngrok -g

      - name: Run ngrok
        run: ngrok http 9000

      - name: WebPageTest
        uses: abdulsuhail/web-test@master
        with:
          apiKey: ${{ secrets.WPT_API_KEY }}
          urls: |
            https://www.google.com/search?q=mac+m1+chip

          label: 'GitHub Action Test'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          wptOptions: '/.github/workflows/wpt-options.json'